### ISSUE TITLE
R output

### ISSUE THREAD

**Issue by rrmitrowsky** [aholanda/rrwg#6]
1) I do not use ggplot2, I prefer instead to use base graphics. Please include an option to

* plot using ggplot2 -- as you do

or

* plot using the following script which I made yesterday at home

df <- read.table("rrwg.dat", header=T)
n <- seq(1,nrow(df))
nboxes <- ncol(dt)/2
if ((nboxes %% 2) == 1) nboxes <- nboxes + 1
par(mfrow=c(nboxes/2,2),mar=c(0.5,1,0.1,0.5))
for (i in seq(1,ncol(df),2)) {
    plot(n,df[,i]/n,type="l",ylim=c(0,1),axes=F,frame.plot=F,lwd=1.5);
    axis(1,labels=F)
    axis(2,labels=F)
    lines(n,df[,i+1]/n, type="l", col="red", lwd=1.5);
}
rm(list=ls())

I prefer to not to call a browser to open the generated pdf -- so I comented the last two lines of
___main__.py (I sourced at the R prompt the script above after each iteration)

2) Please observe that the output that can be vissualy interpreted (and hence seen via a plot) is the fcation of counts and not the total counts. Please if you do not maind, change to fractions.

**Comment by aholanda** [comment]
The fraction could be obtained using R.

**Comment by aholanda** [comment]
- R script file is not generated anymore
- Normalization of number of visits was done in the code
